project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Youbin He"
  site-url: https://heyoubin.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/HeYoubin/HeYoubin.github.io
  repo-actions: [edit, issue]

  navbar:
    background: "#355E3B"
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: Res_Pro.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Code"
        href: codes.qmd
      - text: "CV"
        href: Youbin_He_CV.pdf
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: styles.scss
    toc: true
    toc-position: right
    toc-depth: 3
